**Intro Numpy**

In [1]:
import numpy as np

**Creating Arrays**

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [6]:
# Access element of array 
a[2] = 10 #change 3rd element to 1
a

array([ 1,  2, 10,  5,  7, 12])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 1, 11) #creates an array of size level between 0 & 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

**Multi-Dimensional Arrays**

In [ ]:
np.zeros((5,2)) #5 rows 2 columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [20]:
n[0,1] = 20 #change element of first row, and second column to 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
n[2] = [1, 1, 1]  #change last row to 1's
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [25]:
n[:, 2] = [0, 1, 2] #Change last column to 0,1,2
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

**Randomly Generated Arrays**

In [ ]:
np.random.rand(5, 2)

array([[0.77833075, 0.47701885],
       [0.24178591, 0.80820085],
       [0.4184895 , 0.13613831],
       [0.22523701, 0.22695272],
       [0.34252211, 0.98781846]])

In [ ]:
np.random.seed(10) #fixing seed number, randomisation stays constant
np.random.rand(5, 2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [30]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2)) #array with random generated integers

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

**Element-wise Operations**

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
a * 2 #every element of an array is multiplied by 2
a / 100 #every element of an array is divided by 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [34]:
b = (10 + (a*2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [36]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

**Comparison Operations**

In [37]:
a >= 2 #Finding which element of an aray are greater than or equal to 2

array([False, False,  True,  True,  True])

In [39]:
a[a > b] #which elements of a are greater than b 

array([2, 3, 4])