**Linear Algebra**

In [4]:
import numpy as np

In [11]:
u = np.array([2,3,4,5])  #vector 1
v = np.array([6,7,8,9])  # vector 2

u.shape[0]
v.shape[0]

4

In [ ]:
def vector_vector_multiplication(u, v):  # function to create dot product (Explanation)
    assert u.shape[0] == v.shape[0]      #ensures that both vectors are the same size for dot product
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

vector_vector_multiplication(u, v)



np.int64(110)

In [18]:
u.dot(v) # presents same outcome

np.int64(110)

In [20]:
U = np.array([
    [1,1,2],
    [2,2,3],
    [3,3,4]
])

In [25]:
def matrix_vector_multiplication(U, v):
    
    assert U.shape[1] == v.shape[0]  #Number of columns on U (2nd Dimension) should mathc number of rows (v)
    
    no_of_rows = U.shape[0]
    
    result = np.zeros(no_of_rows)
    
    for i in range(no_of_rows):
        result[i] = vector_vector_multiplication(U[i], v) 
    
    return result

In [29]:
matrix_vector_multiplication(U, v) #returns error as U has 3 columns, v has 4 rows

AssertionError: 

In [27]:
P = np.array([
    [1,1,2, 2],
    [2,2,3, 3],
    [3,3,4, 4]
])

matrix_vector_multiplication(P, v)

array([ 47.,  77., 107.])

In [30]:
V = np.array([
    [2,3,4,5],
    [6,7,8,9],
    [10,11,12,13]
])

In [31]:
def matrix_matrix_multiplication(U, V):
    
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        Vi = V[:, i]
        UVi = matrix_vector_multiplication(U, Vi)
        result[:, i] = UVi
        
    return result
    

In [32]:
matrix_matrix_multiplication(U, V)

array([[28., 32., 36., 40.],
       [46., 53., 60., 67.],
       [64., 74., 84., 94.]])

In [33]:
U.dot(V) #returns same result

array([[28, 32, 36, 40],
       [46, 53, 60, 67],
       [64, 74, 84, 94]])